CREATE TABLE IF NOT EXISTS `character_craft_fails` (
	`char_name` VARCHAR(35) CHARACTER SET UTF8 NOT NULL DEFAULT '',
	`crafter_name` VARCHAR(35) CHARACTER SET UTF8 NOT NULL DEFAULT '',
	`time` bigint(20) NOT NULL DEFAULT '0',
	PRIMARY KEY  (`time`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;